<%
distrib, infos    = ENV.fetch('DISTRIB', 'debian:stretch/9').split(':')
codename, version = infos.split('/')
%>
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: salt_solo
  formula: rkhunter

  # Install Salt from official repositories
  salt_install: apt
  salt_version: latest
  salt_apt_repo: http://repo.saltstack.com/apt/<%= distrib %>/<%= version %>/amd64
  salt_apt_repo_key: http://repo.saltstack.com/apt/<%= distrib %>/<%= version %>/amd64/latest/SALTSTACK-GPG-KEY.pub

  # Don't install Chef
  require_chef: false

  # Configure Salt
  state_top:
    base:
      '*':
        - rkhunter.config

  pillars:
    top.sls:
      base:
        '*':
          - rkhunter
    rkhunter.sls:
      rkhunter:
        config:
          allow_ssh_root_user: 'yes'
        default:
          run_check_on_battery: true

platforms:
  - name: <%= distrib %>-<%= codename %>
    driver_config:
      image: "<%= distrib %>:<%= codename %>"
      platform: <%= distrib %>

verifier:
  name: inspec
  format: progress

suites:
  - name: rkhunter
